# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: checkout 
        uses: actions/checkout@v3
        with:
            submodules: recursive

      # Runs a single command using the runners shell
      - name: Docker Build
        uses: ./
        id: Build
        with:
          workspace: ${{ github.workspace }}
      - name: Get the output time
        run: echo "The time was ${{ steps.build.outputs.start_time }} -> ${{ steps.build.outputs.end_time }}"   

      - name: Archive production artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build-files
          path: |
            build_docker/*.elf
            build_docker/*.hex
            build_docker/*.disasm
            build_docker/*.map
            build_docker/*.s

